name: Python CI

on:
  push:
    branches:
      - main  # Yalnızca main branşındaki değişikliklerle çalışacak
  pull_request:
    branches:
      - main  # Pull request'lerde de main branşı üzerinde çalışacak

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions'ın çalışacağı ortam (Ubuntu)

    steps:
      # 1. Reposunu checkout et
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python'ı kur
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Python sürümünü belirt

      # 3. Python dosyasını çalıştır
      - name: Run Python script
        run: |
          python main.py  # main.py dosyasını çalıştır

      # 4. Çıktıyı göster (cikti.txt dosyasını oku)
      - name: Show output from cikti.txt
        run: |
          cat cikti.txt  # cikti.txt dosyasının içeriğini göster
          
     
          git commit -m "Update cikti.txt with new results"
          git push
        if: success()  # Eğer önceki adımlar başarılı olduysa
